language: python
# use container-based infrastructure
sudo: required
services:
  - docker
cache:
  pip: true
  timeout: 1000
python:
  - "3.5"
bundler_args: --retry 9
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 # Install git-lfs
 - cd ..
 - curl -sLo - https://github.com/github/git-lfs/releases/download/v1.4.1/git-lfs-linux-amd64-1.4.1.tar.gz | tar xzvf -
 - export PATH=$PATH:`pwd`/git-lfs-1.4.1
 - git lfs install  
 # Download data.
 - cd SwE-toolbox/test
 - git clone https://github.com/TomMaullin/SwE-toolbox-testdata.git data
 # Download testing tools
 - git clone https://github.com/MOxUnit/MOxUnit.git
 - cd ..
jobs:
  include:
    - stage: Results generation
    - script:
      - did=$(sudo docker run -ti -d --rm -v `pwd`:/swe cmaumet/octave-spm)
      - sudo docker exec -t -i $did octave --no-window-system --eval "addpath('/swe');addpath('/swe/test');setuptest('p', 't', 'mat')"
    - script:
      - did=$(sudo docker run -ti -d --rm -v `pwd`:/swe cmaumet/octave-spm)
      - sudo docker exec -t -i $did octave --no-window-system --eval "addpath('/swe');addpath('/swe/test');setuptest('p', 'f', 'mat')"
    - script:
      - did=$(sudo docker run -ti -d --rm -v `pwd`:/swe cmaumet/octave-spm)
      - sudo docker exec -t -i $did octave --no-window-system --eval "addpath('/swe');addpath('/swe/test');setuptest('p', 'f', 'img')"
    - script:
      - did=$(sudo docker run -ti -d --rm -v `pwd`:/swe cmaumet/octave-spm)
      - sudo docker exec -t -i $did octave --no-window-system --eval "addpath('/swe');addpath('/swe/test');setuptest('wb', 't', 'mat')"
    - script:
      - did=$(sudo docker run -ti -d --rm -v `pwd`:/swe cmaumet/octave-spm)
      - sudo docker exec -t -i $did octave --no-window-system --eval "addpath('/swe');addpath('/swe/test');setuptest('wb', 'f', 'mat')"
    - script:
      - did=$(sudo docker run -ti -d --rm -v `pwd`:/swe cmaumet/octave-spm)
      - sudo docker exec -t -i $did octave --no-window-system --eval "addpath('/swe');addpath('/swe/test');setuptest('wb', 't', 'img')"
    - script:
      - did=$(sudo docker run -ti -d --rm -v `pwd`:/swe cmaumet/octave-spm)
      - sudo docker exec -t -i $did octave --no-window-system --eval "addpath('/swe');addpath('/swe/test');setuptest('wb', 'f', 'img')"
before_install:
 # Update docker version
 - sudo apt-get update
 - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
 - git config --global user.name "TravisCI" 
 - git config --global user.email "travis@dummy.com"
 - docker pull cmaumet/octave-spm
